### ISSUE TITLE
How to run development?

### ISSUE THREAD

**Issue by tomasdev** [wallacyyy/webpack-heroku#1]
I use `node server.js` but it doesn't compile the SCSS :|

**Comment by tomasdev** [comment]
Nevermind. I forgot I removed `import '../css/app.scss';` my bad.

**Comment by runiie** [comment]
No problem @tomasdev ! Hook me any problems :)

**Comment by jamcreencia** [comment]
I used `node server.js` too but it doesn't seem to run locally...

**Comment by runiie** [comment]
@jammiii I will test it today and reply here.

**Comment by runiie** [comment]
@jammiii the `server.js` is just exporting a module. You can start by using the `npm start` or just `node app.js` :)
