### ISSUE TITLE
npm run build,  works only in Linux

### ISSUE THREAD

**Issue by jrichardsz** [wallacyyy/webpack-heroku#10]
`NODE_ENV=production`

Does not work in Windows. In windows must be:

set NODE_ENV=production.

Please add "cross-env"

**Comment by runiie** [comment]
@jrichardsz I don't have a windows environment available right now, do you mind to open a PR with the cross-env ? I suppose it will fix the #9 too ?

**Comment by runiie** [comment]
Fixed on #11
