### ISSUE TITLE
Express wildcard routing breaks

### ISSUE THREAD

**Issue by teodorpatras** [wallacyyy/webpack-heroku#12]
Hi, thanks a lot for this cool starting project, I find it very helpful. What I am trying to do currently, is to add the `react-router` to handle different paths within my app and for that, I needed to make this change in the `server.js`: 

```
app.get('*', function(_, res) {
    res.sendFile(indexPath)
})
```

As soon as that change has been applied, everything breaks, the react app is not shown anymore in the web page, and I only get a weird error in the web browser console: `bundle.js:1 Uncaught SyntaxError: Unexpected token <`, and when I look into that file `bundle.js` I see it is basically the content of `index.html` inside of a `js` file.

Do you have any idea why this wildcard routing broke the whole flow? I would really appreciate if you could help.

**Comment by teodorpatras** [comment]
Fixed: https://github.com/glenjamin/webpack-hot-middleware/issues/26#issuecomment-144941322

**Comment by runiie** [comment]
Thanks for the input @teodorpatras :) Glad it worked for you !
