### ISSUE TITLE
Production Server does not work

### ISSUE THREAD

**Issue by PedroS11** [wallacyyy/webpack-heroku#13]
Good night, 

If i run the server in dev mode it appears the "Change me" but in production mode when i enter the site its all blank. Any idea how can i fix it? 

Thank you,

Pedro Silva

**Comment by runiie** [comment]
I will take a look today 👍  This happens straight from the repo or you added something in the project ? @PedroS11

**Comment by PedroS11** [comment]
Straight from the repo, i clone it and when run in prod mode it's all blank but in dev everything works fine. If you could fix it it will be great, react project with hot reloading and dev/prod functionality is the best basic repo i found. The others are very complex and full with unnecessary packages.

**Comment by runiie** [comment]
So, I took a look. In production mode you need to run the `npm run build` first.
You have two ways to deploy to production with `webpack`: 

1. Keep the `webpack` libraries on `dependencies` and add a post build hook on the `package.json`

2. Keep the `webpack` libraries on `devDependencies`, generate your bundle locally and push to the production afterwards.

I wrote a more detailed [post](http://ditrospecta.com/javascript/react/es6/webpack/heroku/2015/08/08/deploying-react-webpack-heroku.html) about it, you can take a look. Any doubt let me know 😄 

@PedroS11
