### ISSUE TITLE
Error when running npm start

### ISSUE THREAD

**Issue by c-poulsen** [wallacyyy/webpack-heroku#15]
Running npm start returns
ERROR in ./src/index.js
Module build failed: ReferenceError: Unknown plugin "react-transform" specified in "/Users/me/Desktop/webpack-heroku/.babelrc.env.development" at 0, attempted to resolve relative to "/Users/me/Desktop/webpack-heroku"

**Comment by runiie** [comment]
@c-poulsen I could not reproduce your problem on my machine, I downloaded a clean version of the repo, `npm i` and `npm start`. Everything is working fine for me, are you running `npm install` ?

**Comment by c-poulsen** [comment]
@wallacyyy Yes, I did both. I just downloaded a clean version as well - same error
It starts the server, but makes no updates on change. Also the page is blank in dev since no bundle.js was generated

**Comment by c-poulsen** [comment]
@wallacyyy I just updated node, and tried again, and it seems to work now. Sorry for the inconvenience and awesome repo btw

**Comment by runiie** [comment]
Nah, it's fine :) ! Glad that worked for you ! @c-poulsen
