### ISSUE TITLE
Update to Webpack 2

### ISSUE THREAD

**Issue by runiie** [wallacyyy/webpack-heroku#16]
The title says all :) Feel free to grab this issue if you want to contribute !

**Comment by jephjohnson** [comment]
Hey there @wallacyyy - I forked and updated to Webpack 2 and updated all the dependencies. I baked in redux also with a simple div toggle if anyone needs it. Cheers Jeph 

https://github.com/jephjohnson/webpack-heroku

**Comment by runiie** [comment]
Hey @jephjohnson, this is really awesome ! Do you mind open a PR ? I will integrate on the repo :tada:

**Comment by jephjohnson** [comment]
@wallacyyy - No worries, thanks taking the time to create your repo and documentation 👍
