### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by aryalprakash** [wallacyyy/webpack-heroku#2]
I am getting this error on browser console after deploying on heroku server. Can you help me resolve this?
"Uncaught Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration."

**Comment by runiie** [comment]
I'm taking a look @aryalprakash 👍

**Comment by runiie** [comment]
@aryalprakash,  Can you you pull the changes from master, rebuild with `npm run build` and check if it's working now ?

**Comment by aryalprakash** [comment]
Thanks @wallacyyy. I got no errors during executing npm run build but the error still exists when deployed to server.

**Comment by runiie** [comment]
Did you commited your bundle.js after run the the build and before you push to Heroku ? I got no errors here o.o

**Comment by aryalprakash** [comment]
Yeah :(
You can check it yourself 
http://webpackher.herokuapp.com/

**Comment by thehulke** [comment]
hey there, same issue here :)

**Comment by katgus** [comment]
Change your 'babel.rc' to this: 

```
{
  "presets": [
    "es2015",
    "react",
    "stage-0"
  ],
  "env": {
    "development/client": {
      "presets": [
        "react-hmre"
      ]
    }
  }
}
```

and your 'webpack.prod.config.js' plugins section to this:

```
  plugins: [
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.UglifyJsPlugin({
      minimize: true,
      compress: {
        warnings: false
      }
    }),
    new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': JSON.stringify('production'),
        'BABEL_ENV': JSON.stringify('production')
      }
    })
  ],
```

And your 'webpack.dev.config.js' plugins section to this:

```
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),

    new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': JSON.stringify('development'),
        'BABEL_ENV': JSON.stringify('development/client')
      }
    })
  ],
```

Don't forget `npm run build` then commit and push to heroku again.

**Comment by runiie** [comment]
I will look again this today for sure :+1:

**Comment by domhede** [comment]
Yep same issue for me.

**Comment by runiie** [comment]
Can someone confirm if #3 fixed this plz ? I think yes but I didn't had too much time to look it in detail.

**Comment by vitorlans** [comment]
@wallacyyy Hi, working now at production. problem fixed. thanks

**Comment by runiie** [comment]
Thanks to @masterfung, he solved it :) ! @vitorhs
