### ISSUE TITLE
Can I use "extract-text-webpack-plugin"?

### ISSUE THREAD

**Issue by Kalita-Roman** [wallacyyy/webpack-heroku#8]
In your example, styles css is being adding to tag <head></head> in file index.html.
But I want create separate file "bundle.css". I use "extract-text-webpack-plugin" for this, but it don't work livereload for styles in this case.
How can I create separate file "bundle.css" with livereload?
Sorry for my English.

**Comment by runiie** [comment]
@Kalita-Roman, I never user this plugin before but I took a look on the repo and found this [issue](https://github.com/webpack/extract-text-webpack-plugin/issues/30) with people suggesting another setup, see if it helps maybe.
