### ISSUE TITLE
Module build failed: ReferenceError: Unknown plugin "react-transform" 

### ISSUE THREAD

**Issue by jrichardsz** [wallacyyy/webpack-heroku#9]
Hi.

After npm install, i executed npm start and I got this error:

`Module build failed: ReferenceError: Unknown plugin "react-transform" specified in "..\\some_path\\webpack-heroku\\.babelrc.env.development" at 0, attempted to resolve relative to "..\\some_path\\webpack-heroku"
`
windows 7
node version v4.6.1

Thanks.

**Comment by runiie** [comment]
Fixed on #11
